 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  nextqa: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /nas-ssd/shoubin/datasets/nextqa/train.json
          storage: /nas-ssd/shoubin/datasets/nextqa/train.json
        val:
          url: /nas-ssd/shoubin/datasets/nextqa/val.json
          storage: /nas-ssd/shoubin/datasets/nextqa/val.json
        test:
          url: /nas-ssd/shoubin/datasets/nextqa/val.json
          storage: /nas-ssd/shoubin/datasets/nextqa/val.json
      videos:
        storage: /nas-hdd/shoubin/videos/vidor/videos/
